on:
  workflow_dispatch:
  release:
    types: [created]

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run package
      - run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
